// assets/vue/components/Right/Right.vue
<template>
  <div class="col-7 px-0">
    <div class="px-4 py-5 chat-box bg-white" ref="messagesBody">
      <template v-for="(message, index, key) in MESSAGES">
        <Messages :messages="message" />
      </template>
    </div>
    <Form />
  </div>
</template>

<script>
  import {mapGetters} from "vuex";

  import Messages from "./Messages";
  import Form from "./Form";

  export default {
    name : "Right",
    data : () => ({
      eventSource : null
    }),
    components : {
      Form,
      Messages
    },
    computed : {
      ...mapGetters(["HUBURL"]),
      MESSAGES(){
        return this.$store.getters.MESSAGES(this.$route.params.id);
      }
    },
    methods : {
      scrollDown(){
        this.$refs.messagesBody.scrollTop = this.$refs.messagesBody.scrollHeight;
      },
      addMessage(data){
        this.$store.commit("ADD_MESSAGE", {
          conversationId : this.$route.params.id,
          payload : data
        })
      }
    },
    mounted() {
      const vm = this;
      this.$store.dispatch("GET_MESSAGES", this.$route.params.id)
      .then(() => {
        this.scrollDown();

        if(this.eventSource === null){
          let url = new URL(this.HUBURL);
          url.searchParams.append('topic',`/conversations/${this.$route.params.id}`);

          this.eventSource = new EventSource(url, {
            withCredentials: true
          });

          this.eventSource.onmessage = function (event) {
            vm.addMessage(JSON.parse(event.data));
          }
        }
      });
    },
    watch : {
      MESSAGES : function (val) {
        this.$nextTick(() => {
          this.scrollDown();
        })
      }
    },
    beforeDestroy() {
      if(this.eventSource instanceof EventSource){
        this.eventSource.close();
      }
    }
  }
</script>

// assets/react/components/Right/Right.js
import React, { createRef, useEffect, useLayoutEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'

import { fetchMessages, setMessage } from '../../store/actions/message'

import Message from './Message'
import Form from './Form'

export default function Right({ ...props }) {
    const bodyRef = createRef()

    const conversationId = props.match.params.id

    const dispatch = useDispatch()

    const { messages } = useSelector((state) => state.messages)
    const { hubUrl } = useSelector((state) => state.conversations)

    useEffect(() => {
        dispatch(fetchMessages(conversationId))
    }, [])

    // Messages Scroll
    const scrollDown = () => {
        bodyRef.current.scrollTop = bodyRef.current.scrollHeight
    }

    useLayoutEffect(() => {
        scrollDown()
    }, [messages])

    useEffect(() => {
        if (hubUrl) {
            let url = new URL(hubUrl)

            url.searchParams.append('topic', `/conversations/${props.match.params.id}`)

            const eventSource = new EventSource(url, {
                withCredentials: true
            })

            eventSource.onmessage = function (event) {
                const data = JSON.parse(event.data)

                dispatch(setMessage(data, data.conversation.id))
            }
        }
    }, [hubUrl])

    return (
        <div className="col-7 px-0">
            <div className="px-4 py-5 chat-box bg-white" ref={bodyRef}>
                {messages
                    ? messages.map((message, key) => {
                          return <Message message={message} key={key} />
                      })
                    : '...'}
            </div>
            <Form conversationId={conversationId} />
        </div>
    )
}
